version: 2
executorType: machine
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run: java -version
      - run: mvn -B clean install
